name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Compile and Run Tests
      run: |
        # Show current directory contents
        ls -la
        
        # Compile all Java files
        javac LoginApp.java LoginAppST.java
        
        # Run the test class
        java LoginAppST

    - name: Check Test Results
      run: |
        if [ $? -eq 0 ]; then
          echo "Tests passed successfully"
          exit 0
        else
          echo "Tests failed"
          exit 1
        fi
