name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: List Directory Contents
      run: |
        pwd
        ls -la
        ls -la src/
        ls -la test/

    - name: Compile and Run Tests
      run: |
        mkdir -p build/test
        javac -cp "src:test" src/LoginApp.java test/LoginAppST.java -d build
        cd build
        java LoginAppST
